CREATE TABLE PAIS_T
(
ID_PAIS INT IDENTITY (1, 1) PRIMARY KEY,
NOME_PAIS VARCHAR(100) UNIQUE NOT NULL,
CONTINENTE VARCHAR(100) NOT NULL,
)

CREATE TABLE ESTADO_T
(
ID_ESTADO INT IDENTITY (1,1) PRIMARY KEY,
NOME_ESTADO VARCHAR(100) NOT NULL,
UF CHAR(2),
ID_PAIS INT FOREIGN KEY REFERENCES PAIS_T(ID_PAIS)
)

CREATE TABLE CIDADE_T
(
ID_CIDADE INT IDENTITY (1,1) PRIMARY KEY,
NOME_CIDADE VARCHAR(100) NOT NULL,
ID_ESTADO INT FOREIGN KEY REFERENCES ESTADO_T(ID_ESTADO),
RENDA DECIMAL(18, 4)
)

ALTER TABLE CIDADE_T DROP COLUMN RENDA
ALTER TABLE CIDADE_T
ADD DATA_REGISTRO DATETIME DEFAULT GETDATE()

INSERT INTO PAIS_T
(NOME_PAIS, CONTINENTE) 
VALUES 
('BRASIL','AMÉRICA DO SUL'),
('INDIA', 'ÁSIA')

INSERT INTO ESTADO_T
(NOME_ESTADO, UF, ID_PAIS)
VALUES
('SÃO PAULO', 'SP', 1),
('BAHIA', 'BA', 1),
('MAHARASHTRA', NULL, 2)

INSERT INTO CIDADE_T
(NOME_CIDADE, ID_ESTADO)
VALUES
('MARILIA', 1),
('SALVADOR', 2),
('BOMBAI', 3)

SELECT * FROM PAIS_T
SELECT * FROM ESTADO_T
SELECT * FROM CIDADE_T
