DROP TABLE IF EXISTS #ANO

CREATE TABLE #ANO(
ID_ANO INT PRIMARY KEY IDENTITY(1, 1),
ANO INT NOT NULL
);

DROP TABLE IF EXISTS #MES

CREATE TABLE #MES(
ID_MES INT PRIMARY KEY IDENTITY(1, 1),
MES INT NOT NULL,
);

SELECT * FROM #MES


DROP TABLE IF EXISTS #MODELO

CREATE TABLE #MODELO(
ID_MODELO INT PRIMARY KEY IDENTITY(1, 1),
DESCRICAO VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS #FABRICANTE

CREATE TABLE #FABRICANTE(
ID_FABRICANTE INT PRIMARY KEY IDENTITY(1, 1),
NOME VARCHAR(100),
CIDADE VARCHAR(100),
ENDERECO VARCHAR(100),
UF VARCHAR(100),
TELEFONE VARCHAR(100),
CONTATO VARCHAR(100)
);

DROP TABLE IF EXISTS #VEICULOS

CREATE TABLE #VEICULOS(
ID_VEICULO INT PRIMARY KEY IDENTITY(1, 1),
DESCRICAO VARCHAR(100),
VALOR FLOAT,
ID_MODELO INT FOREIGN KEY REFERENCES #MODELO(ID_MODELO),
ID_FABRICANTE INT FOREIGN KEY REFERENCES #FABRICANTE(ID_FABRICANTE),
ID_ANO_FABRICACAO INT FOREIGN KEY REFERENCES #ANO(ID_ANO),
DATA_COMPRA DATE,
);

DROP TABLE IF EXISTS #VENDASANUAIS

CREATE TABLE #VENDASANUAIS(
ID_VENDAS INT PRIMARY KEY IDENTITY(1, 1),
QTD FLOAT,
ID_VEICULO INT FOREIGN KEY REFERENCES #VEICULOS(ID_VEICULO),
ID_ANO_VENDA INT FOREIGN KEY REFERENCES #ANO(ID_ANO),
ID_MES_VENDA INT FOREIGN KEY REFERENCES #MES(ID_MES),
);

--1
ALTER TABLE #VEICULOS ALTER COLUMN DESCRICAO VARCHAR(30) NOT NULL;
--2
ALTER TABLE #VEICULOS ADD STATUS_VEICULO VARCHAR(20);
ALTER TABLE #VEICULOS DROP COLUMN STATUSVEICULO;
--3
ALTER TABLE #FABRICANTE DROP COLUMN CONTATO;
--4
-----
--5
ALTER TABLE #VENDASANUAIS ADD CONSTRAINT CKQTD CHECK (QTD > 1 AND QTD < 10000)
--6
INSERT INTO 
#ANO (ANO)
VALUES
('2016'),
('2017'),
('2018'),
('2019'),
('2020'),
('2021'),
('2022');
--7
INSERT INTO 
#MODELO (DESCRICAO)
VALUES 
('LST'),
('KS'),
('RS');
--8
ALTER TABLE #MES ADD DESCRICAOMES VARCHAR(255);
--9
INSERT INTO #MES (MES)
VALUES
(1),
(2),
(3),
(4),
(5),
(6),
(7),
(8),
(9),
(10),
(11),
(12);

UPDATE #MES SET DESCRICAOMES='JANEIRO' WHERE ID_MES=1
UPDATE #MES SET DESCRICAOMES='FEVEREIRO' WHERE ID_MES=2
UPDATE #MES SET DESCRICAOMES='MARÇO' WHERE ID_MES=3
UPDATE #MES SET DESCRICAOMES='ABRIL' WHERE ID_MES=4
UPDATE #MES SET DESCRICAOMES='MAIO' WHERE ID_MES=5
UPDATE #MES SET DESCRICAOMES='JUNHO' WHERE ID_MES=6
UPDATE #MES SET DESCRICAOMES='JULHO' WHERE ID_MES=7
UPDATE #MES SET DESCRICAOMES='AGOSTO' WHERE ID_MES=8
UPDATE #MES SET DESCRICAOMES='SETEMBRO' WHERE ID_MES=9
UPDATE #MES SET DESCRICAOMES='OUTUBRO' WHERE ID_MES=10
UPDATE #MES SET DESCRICAOMES='NOVEMBRO' WHERE ID_MES=11
UPDATE #MES SET DESCRICAOMES='DEZEMBRO' WHERE ID_MES=12

--10
INSERT INTO #FABRICANTE (NOME, CIDADE, ENDERECO, UF, TELEFONE)
VALUES
('Triumph', 'SÃO PAULO', 'RUA ANTONIO DA SILVA', 'SP', '4459-1351'),
('KTM', 'RIO DE JANEIRO', 'AV JARDIM SILVEIRA', 'RJ', '3256-2365'),
('Kynco', 'SÃO PAULO', 'RUA DOS ANJOS', 'SP', '3526-1014');
--11
INSERT INTO #VEICULOS (DESCRICAO, VALOR, DATA_COMPRA, )
VALUES
('TIGER', 5051, '2022-01-23'),
('ECX 450', 7000, '2021-08-10'),
('DOWNTOWN', 1000, '2022-10-30' )

SELECT * FROM #ANO
SELECT * FROM #FABRICANTE
SELECT * FROM #VEICULOS
SELECT * FROM #MES
SELECT * FROM #MODELO
