SELECT * FROM FILMES

SELECT * INTO #FILMES FROM FILMES

SELECT * FROM #FILMES

SELECT DISTRIBUIDOR FROM #FILMES

SELECT BILHETERIA_DOLAR * 5 BILHETERIA_REAL FROM #FILMES 
SELECT BILHETERIA_DOLAR BILHETERIA_REAL FROM #FILMES 

SELECT ANO, FILME FROM #FILMES

SELECT TOP(5) * FROM #FILMES ORDER BY 1

SELECT BILHETERIA_DOLAR * 0.3 CUSTO_FILME FROM #FILMES

SELECT BILHETERIA_DOLAR - BILHETERIA_DOLAR * 0.3 LUCRO FROM #FILMES

SELECT CONCAT('FOI DISTRIBUIDO PELA EMPRESA:', DISTRIBUIDOR) FROM #FILMES

SELECT FILME FROM #FILMES WHERE FILME='DEADPOOL' OR FILME='TITANIC'

SELECT ANO FROM #FILMES WHERE ANO >= 2010 AND ANO < 2015 GROUP BY ANO

SELECT BILHETERIA_DOLAR FROM #FILMES WHERE Bilheteria_dolar > 1000000000

SELECT FILME, ANO FROM #FILMES WHERE Bilheteria_dolar < 1000000000 AND ANO > 2000

SELECT FILME, ANO, BILHETERIA_DOLAR FROM #FILMES WHERE DISTRIBUIDOR = 'WARNER BROS. PICTURES'

SELECT * FROM #FILMES WHERE DISTRIBUIDOR != 'NEW LINE CINEMA'

SELECT * FROM #FILMES WHERE ANO > 2001 ORDER BY 1

SELECT * FROM #FILMES WHERE DISTRIBUIDOR IS NULL

SELECT FILME, RANKING FROM #FILMES WHERE RANKING > 50 AND RANKING < 80 OR ANO = 2007

SELECT FILME, ANO, DISTRIBUIDOR 
FROM #FILMES 
WHERE ANO = 1977 AND DISTRIBUIDOR = '20TH CENTURY FOX' 
OR ANO = 1982 AND DISTRIBUIDOR = 'UNIVERSAL PICTURES'

